// The command table the fakes answer `commands.list` with: a slice of the harness's
// (`Troupe.Commands`), enough for a palette to have sections, aliases, a command that
// needs an argument, one a pod cannot run, and an agent.

import type { CommandEntry } from "../../src/types.js";

const arg = (name: string, required: boolean, kind: string) => ({ name, required, kind });

export const COMMANDS: CommandEntry[] = [
  {
    name: "cancel",
    aliases: [],
    section: "session",
    summary: "Stop a branch mid-turn and remove its window",
    usage: "/cancel [window]",
    args: [arg("window", false, "window")],
    availability: "window",
    source: "builtin",
    detail: "Stops the agent in the activated window, or in the one named, and removes the window.",
    example: "/cancel 2",
  },
  {
    name: "merge",
    aliases: [],
    section: "session",
    summary: "Land a worktree branch on the checkout",
    usage: "/merge [window]",
    args: [arg("window", false, "window")],
    availability: "local",
    source: "builtin",
    detail: "Commits what the branch left uncommitted and merges its branch into the checkout.",
    example: "/merge 2",
  },
  {
    name: "goal",
    aliases: [],
    section: "session",
    summary: "Set, show or clear the session's goal",
    usage: "/goal [text | clear]",
    args: [arg("text", false, "text")],
    availability: "always",
    source: "builtin",
    detail: "Every later turn works towards the goal. /goal alone shows it, /goal clear clears it.",
    example: "/goal make the suite green",
  },
  {
    name: "sessions",
    aliases: ["resume"],
    section: "navigate",
    summary: "This directory's sessions, newest first",
    usage: "/sessions [n | id]",
    args: [arg("session", false, "text")],
    availability: "always",
    source: "builtin",
    detail: "Enter switches to one.",
    example: "/resume 2",
  },
  {
    name: "upload",
    aliases: [],
    section: "workspace",
    summary: "Send a local file into the session's own mount",
    usage: "/upload <path>",
    args: [arg("path", true, "file")],
    availability: "always",
    source: "builtin",
    detail: "The file is read on this machine and written to session:/<name>.",
    example: "/upload notes.md",
  },
  {
    name: "settings",
    aliases: [],
    section: "setup",
    summary: "Settings, and the keys and concepts worth knowing",
    usage: "/settings",
    args: [],
    availability: "always",
    source: "builtin",
    detail: "Every tweakable setting with its value and what it does.",
    example: null,
  },
  {
    name: "help",
    aliases: ["?"],
    section: "setup",
    summary: "This list: every command, what it does and how to type it",
    usage: "/help",
    args: [],
    availability: "always",
    source: "builtin",
    detail: "Type to filter; Enter runs; Esc closes.",
    example: null,
  },
  {
    name: "build",
    aliases: [],
    section: "agents",
    summary: "Implement a change in the checkout.",
    usage: "/build <prompt>",
    args: [arg("prompt", true, "text")],
    availability: "local",
    source: "agent",
    detail: "Implement a change in the checkout.",
    example: null,
  },
  {
    name: "quit",
    aliases: ["exit", "q"],
    section: "quit",
    summary: "Leave the terminal client; the session carries on",
    usage: "/quit",
    args: [],
    availability: "always",
    source: "builtin",
    detail: "Sessions live in the daemon, so nothing stops.",
    example: null,
  },
];
