defmodule Troupe.Memory do
  @moduledoc """
  The project brief's text (Decisions 649 and 838): the facts a repository's memory keeps,
  as `.troupe/memory.md` shows them to a person and as a system prompt carries them.

  Pure. `Troupe.Memory.Facts` keeps the facts, one per line of
  `.troupe/memory/facts.jsonl`, and `Troupe.Session.Memory` says where; nothing here
  touches disk. A fact is durable but never authoritative: it is not an event, replay
  ignores it, and `list_files`/`grep`/`read_file` remain the truth about current contents.

  - **The view.** `.troupe/memory.md` is generated from the facts (`view/2`): a YAML
    frontmatter (`built_at`, `head`, `survey`, and `generated`, the hash of the body as it
    was written), a line saying the file is generated and where the facts are, then one
    `## ` section per kind with a fact per list item. `units/1` reads a body back item by
    item, which is how a person's edit of the view, and a brief written before there were
    facts, become facts. Parsing stays lossless: sections keep their order, a heading
    nobody recognises is kept, and text before the first heading is a titleless section.
  - **The prompt.** Only `command` and `convention` facts are in it (`prompt/2`), what
    agents follow, within `memory_max_chars`: each as written, one that may no longer be
    true saying so and why, then one line naming `recall` and how many other facts it
    answers. Overview, layout, notes and what did not work come through `recall`.
  """

  @type section :: {String.t(), String.t()}
  @type t :: %__MODULE__{
          built_at: DateTime.t() | nil,
          head: String.t() | nil,
          files: non_neg_integer() | nil,
          survey: non_neg_integer() | nil,
          generated: String.t() | nil,
          sections: [section()]
        }

  @typedoc "A fact as `Troupe.Memory.Facts` keeps it: string keys, `status` once read."
  @type fact :: %{String.t() => term()}

  @typedoc "What a prompt carries: the core's facts with their status, and the rest by kind."
  @type core :: %{facts: [fact()], others: %{String.t() => pos_integer()}}

  defstruct built_at: nil, head: nil, files: nil, survey: nil, generated: nil, sections: []

  # The version of the librarian's survey: what it reads and what the brief leaves to other
  # files. Recorded as `survey` when a brief is built, and raised whenever the survey would
  # write a different brief for the same repository, so a session can say that a brief was
  # written under an older one (Decision 827). Nothing rebuilds a brief for it.
  @survey 1

  @kinds ~w(command convention overview layout note negative)
  @core ~w(command convention)

  # The view's sections, one per kind, in the order it shows them.
  @titles [
    {"overview", "Overview"},
    {"layout", "Layout"},
    {"command", "Commands"},
    {"convention", "Conventions"},
    {"negative", "What did not work"},
    {"note", "Notes"}
  ]

  @max_chars 6_000
  @max_age_days 7

  @facts_file ".troupe/memory/facts.jsonl"

  @header "> Generated by Troupe from `#{@facts_file}`, where each fact is kept with what it " <>
            "rests on and who checked it, and rewritten whenever a fact changes. An edit here " <>
            "is not lost: a line you add is read back as a fact of your own, and a line you " <>
            "take out forgets its fact."

  @header_mark "> Generated by Troupe"

  @preamble """
  What earlier agents in this repository found out and checked, kept as facts: use
  these commands and follow these conventions rather than working them out again. Each
  was checked when it was written down. One marked "may no longer be true" rests on a
  file that has changed or gone since, or has not been checked for a while: check it
  before you rely on it. If a command here fails, read the error and the file the
  command comes from rather than running it again.
  """

  @item ~r/^( {0,3})([-*+]|\d{1,9}[.)])( +|$)/
  @fence ~r/^\s*(```|~~~)/

  @doc "An empty brief."
  @spec empty() :: t()
  def empty, do: %__MODULE__{}

  @doc "The view's section titles, in the order it shows them."
  @spec canonical_titles() :: [String.t()]
  def canonical_titles, do: Enum.map(@titles, &elem(&1, 1))

  @doc "The kinds a fact may be, in the order the contract names them."
  @spec kinds() :: [String.t()]
  def kinds, do: @kinds

  @doc "The kinds every prompt carries; the others come through `recall`."
  @spec core_kinds() :: [String.t()]
  def core_kinds, do: @core

  @doc "Where the facts are, from the repository root."
  @spec facts_file() :: String.t()
  def facts_file, do: @facts_file

  @doc "The version of the librarian's survey this build has, which a stamp records."
  @spec survey_version() :: pos_integer()
  def survey_version, do: @survey

  ## Parse and render

  @spec parse(String.t()) :: {:ok, t()} | {:error, term()}
  def parse(content) when is_binary(content) do
    case split_frontmatter(lf(content)) do
      {:ok, meta, body, front} ->
        {:ok,
         %__MODULE__{
           built_at: parse_ts(Map.get(meta, "built_at")),
           head: head(Map.get(meta, "head"), front),
           files: parse_int(Map.get(meta, "files")),
           survey: parse_int(Map.get(meta, "survey")),
           generated: text(Map.get(meta, "generated")),
           sections: sections(body)
         }}

      {:error, reason} ->
        {:error, reason}
    end
  end

  @spec render(t()) :: String.t()
  def render(%__MODULE__{} = m), do: frontmatter(m) <> body(m.sections) <> "\n"

  @doc "The named section's body, or `\"\"`."
  @spec section(t(), String.t()) :: String.t()
  def section(%__MODULE__{} = m, title) do
    case Enum.find(m.sections, fn {t, _text} -> String.downcase(t) == String.downcase(title) end) do
      {_title, text} -> text
      nil -> ""
    end
  end

  @doc "The section titles, in order, without the titleless preamble."
  @spec titles(t()) :: [String.t()]
  def titles(%__MODULE__{sections: sections}),
    do: sections |> Enum.map(&elem(&1, 0)) |> Enum.reject(&(&1 == ""))

  ## The view

  @doc """
  `.troupe/memory.md` for these facts: the frontmatter `meta` gives (`built_at`, `head`,
  `survey`) with `generated`, the hash of the body below it, then the line saying the file
  is generated, then a section per kind, a fact per item, oldest first. With no facts,
  `nil`: there is no view of nothing.
  """
  @spec view([fact()], map()) :: String.t() | nil
  def view([], _meta), do: nil

  def view(facts, meta) do
    body = view_body(facts)

    frontmatter(%__MODULE__{
      built_at: meta[:built_at],
      head: meta[:head],
      survey: meta[:survey],
      generated: digest(body)
    }) <> body
  end

  @doc """
  Whether `content`, a `.troupe/memory.md`, is as it was generated (`:generated`), was
  generated and edited since (`:edited`), or was never generated (`:unstamped`): a body
  whose hash is the `generated` its frontmatter records, one whose is not, and one with
  none recorded. Line endings and the space around the body do not count.
  """
  @spec generated(String.t()) :: :generated | :edited | :unstamped
  def generated(content) do
    with {:ok, meta, body, _front} <- split_frontmatter(lf(content)),
         recorded when is_binary(recorded) <- text(Map.get(meta, "generated")) do
      if recorded == digest(body), do: :generated, else: :edited
    else
      _ -> :unstamped
    end
  end

  @doc """
  A brief's items as facts would hold them, `{kind, claim}`, in order: each list item, each
  paragraph, a fenced block with the line before it that introduces it (one ending in `:`).
  A section is its kind by its title (`Commands` is `command`); one with a title no kind
  has is notes, each led by that title; text before the first heading is notes too, but
  for the line a generated view opens with. Nothing of the text is left out.
  """
  @spec units(t()) :: [{String.t(), String.t()}]
  def units(%__MODULE__{sections: sections}) do
    for {title, text} <- sections,
        kind <- [kind_of_title(title)],
        claim <- claims(text),
        not header?(title, claim),
        do: unit_of(kind, title, claim)
  end

  defp unit_of(nil, "", claim), do: {"note", claim}
  defp unit_of(nil, title, claim), do: {"note", "#{title}: #{claim}"}
  defp unit_of(kind, _title, claim), do: {kind, claim}

  @doc "The items of a section's text, markers taken off, as `units/1` reads them."
  @spec claims(String.t()) :: [String.t()]
  def claims(text) do
    text
    |> lf()
    |> String.split("\n")
    |> Enum.reduce(%{units: [], current: nil, blank: 0, fence: false}, &read_line/2)
    |> close()
    |> Map.fetch!(:units)
    |> Enum.reverse()
    |> Enum.map(&claim_text/1)
    |> Enum.reject(&(&1 == ""))
  end

  @doc """
  How a fact reads as an item of the view: its claim, and for an agent's note the day and
  the agent before it, as notes read before there were facts.
  """
  @spec unit(fact()) :: String.t()
  def unit(%{"kind" => "note", "evidence" => %{"by" => "agent:" <> agent}} = fact) do
    case day(fact["created_at"]) do
      nil -> fact["claim"]
      day -> "#{day} #{agent}: #{fact["claim"]}"
    end
  end

  def unit(fact), do: fact["claim"]

  @doc "The kind a section title stands for, or `nil`."
  @spec kind_of_title(String.t()) :: String.t() | nil
  def kind_of_title(title) do
    want = title |> String.trim() |> String.downcase()

    Enum.find_value(@titles, fn {kind, t} ->
      if want in [kind, String.downcase(t)], do: kind
    end)
  end

  ## The prompt

  @doc """
  What a prompt carries of the core: `text`, the `# Project brief` block with the core's
  facts that fit `:max_chars` (default #{@max_chars}), `""` when none does; `recall`, the
  line naming the `recall` tool and how many facts it answers that the block does not
  carry (`nil` when there are none); and `trimmed`, the characters of the facts left out
  for the cap, which the prompt's provenance reports. `:max_age_days` (default
  #{@max_age_days}) is how long an unanchored fact counts as checked.
  """
  @spec prompt(core() | nil, keyword()) :: %{
          text: String.t(),
          recall: String.t() | nil,
          trimmed: non_neg_integer()
        }
  def prompt(nil, _opts), do: %{text: "", recall: nil, trimmed: 0}

  def prompt(%{facts: facts, others: others}, opts) do
    max = Keyword.get(opts, :max_chars, @max_chars)
    {kept, left} = fit(facts, max, opts)
    trimmed = left |> Enum.map(&String.length(line(&1, opts))) |> Enum.sum()

    rest =
      Enum.reduce(left, others, fn fact, acc -> Map.update(acc, fact["kind"], 1, &(&1 + 1)) end)

    text = if kept == [], do: "", else: "# Project brief\n#{@preamble}\n" <> core_body(kept, opts)
    %{text: text, recall: recall_line(rest, kept != []), trimmed: trimmed}
  end

  @doc """
  The block `prompt/2` gives, with its `recall` line when the agent has the tool
  (`recall: true`, the default), or `""` when there is nothing to say.
  """
  @spec to_prompt(core() | nil, keyword()) :: String.t()
  def to_prompt(core, opts \\ []) do
    core |> prompt(opts) |> compose(Keyword.get(opts, :recall, true))
  end

  @doc "A `prompt/2` result as the prompt has it, its `recall` line in or out."
  @spec compose(%{text: String.t(), recall: String.t() | nil}, boolean()) :: String.t()
  def compose(%{text: text, recall: line}, recall?) do
    cond do
      not recall? or line == nil -> text
      text == "" -> "# Project brief\n" <> line
      true -> text <> "\n\n" <> line
    end
  end

  @doc """
  Whether a fact may no longer be true: an anchor's file changed (`moved`) or is gone
  (`missing`), or, with no anchors, it was last checked longer ago than `:max_age_days`.
  """
  @spec doubtful?(fact(), keyword()) :: boolean()
  def doubtful?(%{"status" => status}, _opts) when status in ["moved", "missing"], do: true

  def doubtful?(%{"status" => "unanchored"} = fact, opts),
    do: aged?(fact["verified_at"], Keyword.get(opts, :max_age_days, @max_age_days))

  def doubtful?(_fact, _opts), do: false

  ## Staleness

  @doc """
  Whether a brief that has facts is worth rebuilding: it was never built (`built_at` nil),
  it was built longer ago than `:max_age_days` (default #{@max_age_days}), or one of the
  core's facts rests on a file that changed or went after it was built (`changed_at`
  later than `built_at`). A core fact a librarian has seen moved and left as it was does
  not make it due again: it stays marked in the prompt until someone re-anchors it.

  HEAD is recorded for a human to read but deliberately does not trigger a refresh:
  every commit would.
  """
  @spec stale?(DateTime.t() | nil, [fact()], keyword()) :: boolean()
  def stale?(built_at, core_facts, opts \\ [])
  def stale?(nil, _core_facts, _opts), do: true

  def stale?(%DateTime{} = built_at, core_facts, opts) do
    aged?(built_at, Keyword.get(opts, :max_age_days, @max_age_days)) or
      Enum.any?(core_facts, &moved_since?(&1, built_at))
  end

  defp moved_since?(%{"status" => status} = fact, built_at) when status in ["moved", "missing"] do
    case parse_ts(fact["changed_at"]) do
      nil -> true
      changed_at -> DateTime.compare(changed_at, built_at) != :lt
    end
  end

  defp moved_since?(_fact, _built_at), do: false

  defp aged?(nil, _max_age_days), do: true

  defp aged?(%DateTime{} = at, max_age_days),
    do: DateTime.diff(DateTime.utc_now(), at, :second) > max_age_days * 86_400

  defp aged?(at, max_age_days), do: aged?(parse_ts(at), max_age_days)

  ## The core in the prompt

  # Whole facts, in order, as long as they fit; one too long for what is left is left out
  # and a shorter one after it may still fit.
  defp fit(facts, max, opts) do
    {kept, left, _used} =
      Enum.reduce(facts, {[], [], 0}, fn fact, {kept, left, used} ->
        cost = String.length(line(fact, opts)) + 1

        heading =
          if Enum.any?(kept, &(&1["kind"] == fact["kind"])), do: 0, else: heading_cost(fact)

        if used + cost + heading <= max,
          do: {[fact | kept], left, used + cost + heading},
          else: {kept, [fact | left], used}
      end)

    {Enum.reverse(kept), Enum.reverse(left)}
  end

  defp heading_cost(fact), do: String.length("## #{title(fact["kind"])}\n") + 1

  defp core_body(facts, opts) do
    for kind <- @core, of_kind = Enum.filter(facts, &(&1["kind"] == kind)), of_kind != [] do
      "## #{title(kind)}\n" <> Enum.map_join(of_kind, "\n", &line(&1, opts))
    end
    |> Enum.join("\n\n")
  end

  defp line(fact, opts) do
    case mark(fact, opts) do
      nil -> item(fact["claim"])
      why -> item(fact["claim"] <> " (may no longer be true: #{why})")
    end
  end

  defp mark(%{"status" => status} = fact, _opts) when status in ["moved", "missing"] do
    changed = Map.get(fact, "changed", [])
    gone = Map.get(fact, "gone", [])

    parts =
      [
        changed != [] && "#{listed(changed)} changed",
        gone != [] && "#{listed(gone)} #{if length(gone) == 1, do: "is", else: "are"} gone"
      ]
      |> Enum.filter(& &1)

    case parts do
      [] -> "a file it rests on changed since it was checked"
      parts -> Enum.join(parts, " and ") <> " since it was checked"
    end
  end

  defp mark(fact, opts) do
    if doubtful?(fact, opts) do
      case day(fact["verified_at"]) do
        nil -> "not checked since it was written"
        day -> "last checked #{day}"
      end
    end
  end

  defp listed(paths), do: Enum.map_join(paths, ", ", &"`#{&1}`")

  defp recall_line(rest, _core?) when map_size(rest) == 0, do: nil

  defp recall_line(rest, core?) do
    n = rest |> Map.values() |> Enum.sum()
    counted = "#{n} #{if core?, do: "more ", else: ""}#{if n == 1, do: "fact", else: "facts"}"

    {verb, them} = if n == 1, do: {"is", "it"}, else: {"are", "them"}

    "#{counted} about this repository (#{breakdown(rest)}) #{verb} kept out of this prompt: " <>
      "the `recall` tool answers #{them} by keyword, kind or path."
  end

  defp breakdown(rest) do
    order = Enum.map(@titles, &elem(&1, 0))

    rest
    |> Enum.sort_by(fn {kind, _n} -> Enum.find_index(order, &(&1 == kind)) || length(order) end)
    |> Enum.map(fn {kind, n} -> "#{n} #{kind_words(kind, n)}" end)
    |> and_list()
  end

  defp kind_words("negative", _n), do: "of what did not work"
  defp kind_words(kind, 1), do: kind
  defp kind_words(kind, _n) when kind in ["overview", "layout"], do: kind
  defp kind_words(kind, _n), do: kind <> "s"

  defp and_list([one]), do: one
  defp and_list(items), do: Enum.join(Enum.drop(items, -1), ", ") <> " and " <> List.last(items)

  ## The view's body

  defp view_body(facts) do
    known = Enum.map(@titles, &elem(&1, 0))
    by_kind = Enum.group_by(facts, &if(&1["kind"] in known, do: &1["kind"], else: "note"))

    # Oldest first; facts written in one second keep the order they are kept in.
    sections =
      for {kind, title} <- @titles, of_kind = Map.get(by_kind, kind, []), of_kind != [] do
        items =
          of_kind
          |> Enum.sort_by(&to_string(&1["created_at"]))
          |> Enum.map_join("\n", &item(unit(&1)))

        "## #{title}\n" <> items
      end

    Enum.join([@header | sections], "\n\n") <> "\n"
  end

  # A fact as a list item: the claim's first line after the marker, every other line
  # indented under it, so a claim of several lines, a list or a fenced block reads back as
  # one item.
  defp item(claim) do
    [first | rest] = String.split(claim, "\n")
    Enum.join(["- " <> first | Enum.map(rest, &if(&1 == "", do: "", else: "  " <> &1))], "\n")
  end

  defp title(kind) do
    Enum.find_value(@titles, String.capitalize(kind), fn {k, t} -> if k == kind, do: t end)
  end

  defp header?("", claim), do: String.starts_with?(claim, @header_mark)
  defp header?(_title, _claim), do: false

  ## Reading items

  # A line at a time: a list item starts at its marker and keeps every line indented under
  # it, and the lines after it before a blank one; a paragraph runs to a blank line; a
  # fenced block is never split, and joins the line before it when that one introduces it.
  defp read_line(line, %{fence: true} = s) do
    s = append(s, line)
    if Regex.match?(@fence, line), do: %{s | fence: false}, else: s
  end

  defp read_line(line, s) do
    s =
      cond do
        String.trim(line) == "" ->
          %{s | blank: s.blank + 1}

        item_start?(line, s.current) ->
          [prefix | _] = Regex.run(@item, line)
          [_whole, indent | _] = Regex.run(@item, line)

          s
          |> close()
          |> Map.merge(%{
            current: {:item, String.length(prefix), String.length(indent), [line]},
            blank: 0
          })

        continues?(line, s) ->
          append(s, line)

        true ->
          s |> close() |> Map.merge(%{current: {:para, [line]}, blank: 0})
      end

    if String.trim(line) != "" and Regex.match?(@fence, line), do: %{s | fence: true}, else: s
  end

  defp item_start?(line, current) do
    case Regex.run(@item, line) do
      [_prefix, indent | _] ->
        case current do
          {:item, _width, base, _lines} -> String.length(indent) <= base
          _other -> true
        end

      nil ->
        false
    end
  end

  # Under an item, an indented line, or any line right after it; under a paragraph, the
  # next line, or a fenced block after a line that introduces it.
  defp continues?(_line, %{current: nil}), do: false

  defp continues?(line, %{current: {:item, _width, _base, _lines}, blank: blank}),
    do: blank == 0 or String.starts_with?(line, "  ")

  defp continues?(line, %{current: {:para, lines}, blank: blank}) do
    blank == 0 or
      (Regex.match?(@fence, line) and String.ends_with?(String.trim_trailing(hd(lines)), ":"))
  end

  defp append(%{current: nil} = s, line), do: %{s | current: {:para, [line]}, blank: 0}

  defp append(%{current: current, blank: blank} = s, line) do
    lines = List.duplicate("", blank) ++ [line]

    current =
      case current do
        {:item, width, base, acc} -> {:item, width, base, Enum.reverse(lines) ++ acc}
        {:para, acc} -> {:para, Enum.reverse(lines) ++ acc}
      end

    %{s | current: current, blank: 0}
  end

  defp close(%{current: nil} = s), do: s

  defp close(%{current: current, units: units} = s),
    do: %{s | units: [current | units], current: nil}

  defp claim_text({:para, lines}), do: lines |> Enum.reverse() |> Enum.join("\n") |> String.trim()

  defp claim_text({:item, width, _base, lines}) do
    [first | rest] = Enum.reverse(lines)
    first = String.slice(first, width..-1//1)
    Enum.join([first | Enum.map(rest, &dedent(&1, width))], "\n") |> String.trim()
  end

  defp dedent(line, width) do
    spaces = String.length(line) - String.length(String.trim_leading(line, " "))
    String.slice(line, min(spaces, width)..-1//1)
  end

  ## Sections

  defp sections(body) do
    body
    |> String.split("\n")
    |> Enum.reduce({[], false}, &collect_line/2)
    |> elem(0)
    |> Enum.map(fn {title, lines} -> {title, lines |> Enum.reverse() |> Enum.join("\n")} end)
    |> Enum.reject(fn {title, text} -> title == "" and String.trim(text) == "" end)
    |> Enum.map(fn {title, text} -> {title, String.trim(text)} end)
    |> Enum.reverse()
  end

  # A `## ` line inside a fenced block is the block's, not a heading.
  defp collect_line(line, {acc, fence?}) do
    heading = if fence?, do: nil, else: Regex.run(~r/^##[ \t]+(.+?)[ \t]*$/, line)
    fence? = if Regex.match?(@fence, line), do: not fence?, else: fence?

    case heading do
      [_whole, title] -> {[{title, []} | acc], fence?}
      nil -> {append_line(acc, line), fence?}
    end
  end

  # Text before the first heading becomes a titleless section, so it round-trips.
  defp append_line([], line), do: [{"", [line]}]
  defp append_line([{title, lines} | rest], line), do: [{title, [line | lines]} | rest]

  defp body(sections), do: Enum.map_join(sections, "\n\n", &render_section/1)

  defp render_section({"", text}), do: text
  defp render_section({title, text}), do: "## #{title}\n#{text}"

  ## Frontmatter

  defp frontmatter(%__MODULE__{
         built_at: nil,
         head: nil,
         files: nil,
         survey: nil,
         generated: nil
       }),
       do: ""

  defp frontmatter(%__MODULE__{} = m) do
    lines =
      [
        m.built_at && "built_at: #{DateTime.to_iso8601(m.built_at)}",
        # Quoted: a short hash of digits and one `e` (`4572e29`) is a number to YAML.
        m.head && "head: #{Jason.encode!(m.head)}",
        m.files && "files: #{m.files}",
        m.survey && "survey: #{m.survey}",
        m.generated && "generated: #{Jason.encode!(m.generated)}"
      ]
      |> Enum.reject(&is_nil/1)

    "---\n" <> Enum.join(lines, "\n") <> "\n---\n\n"
  end

  # Content with no frontmatter is not an error: an empty map plus the whole content. The
  # frontmatter's text comes too, for what YAML does not read as written.
  defp split_frontmatter("---" <> rest) do
    case String.split(rest, ~r/\r?\n---[ \t]*(\r?\n|$)/, parts: 2) do
      [front, body] -> with({:ok, meta} <- parse_yaml(front), do: {:ok, meta, body, front})
      _ -> {:error, :unterminated_frontmatter}
    end
  end

  defp split_frontmatter(content), do: {:ok, %{}, content, ""}

  defp parse_yaml(front) do
    case YamlElixir.read_from_string(front) do
      {:ok, map} when is_map(map) -> {:ok, map}
      {:ok, nil} -> {:ok, %{}}
      {:ok, _other} -> {:error, :frontmatter_not_a_map}
      {:error, reason} -> {:error, reason}
    end
  end

  # What a view's `generated` records: the body's hash, line endings and the space around
  # it aside, so a checkout that turned its line endings into CRLF is still as generated.
  defp digest(body) do
    text = body |> lf() |> String.trim()
    "sha256:" <> Base.encode16(:crypto.hash(:sha256, text), case: :lower)
  end

  defp lf(text), do: String.replace(text, "\r\n", "\n")

  defp parse_ts(nil), do: nil
  defp parse_ts(%DateTime{} = dt), do: dt

  defp parse_ts(value) do
    case DateTime.from_iso8601(to_string(value)) do
      {:ok, dt, _offset} -> dt
      {:error, _reason} -> nil
    end
  end

  defp day(at) do
    case parse_ts(at) do
      nil -> nil
      dt -> dt |> DateTime.to_date() |> Date.to_iso8601()
    end
  end

  defp parse_int(n) when is_integer(n) and n >= 0, do: n

  defp parse_int(s) when is_binary(s) do
    case Integer.parse(s) do
      {n, _rest} when n >= 0 -> n
      _ -> nil
    end
  end

  defp parse_int(_other), do: nil

  defp text(value) when is_binary(value), do: value
  defp text(_other), do: nil

  # The head as it was written. Written quoted now; an older build wrote it bare, and YAML
  # reads a bare short hash of digits and one `e` as a float (`4572e29`) and one of digits
  # with a leading zero as a number without it, so a head YAML did not read as text is taken
  # from its line, one word as written. One that is not a word there (`[4572e29]`) cannot
  # be told from what YAML made of it, and is no head: it is for a person to read, nothing
  # decides on it (`stale?/3`), and the next refresh writes it again.
  defp head(value, _front) when is_binary(value), do: value
  defp head(nil, _front), do: nil

  defp head(_not_text, front) do
    case Regex.run(~r/^head:[ \t]*([^\s#"'\[\]{},&*!|>%@`]+)[ \t]*(?:#[^\r\n]*)?\r?$/m, front) do
      [_line, word] -> word
      nil -> nil
    end
  end
end
