defmodule Mix.Tasks.Troupe.Admin.Assets do
  @shortdoc "Vendor the console's JavaScript from the Phoenix dependencies"

  @moduledoc """
  Build `apps/troupe_plane/priv/static/app.js` out of the JavaScript that ships inside
  `phoenix`, `phoenix_html` and `phoenix_live_view`.

      mix troupe.admin.assets
      mix troupe.admin.assets --check

  ## Why this exists

  The panel's document has always named `/admin/static/app.js`, and no such file has ever
  existed: `Plug.Static` served `app.css` only, and there was no `priv/static` directory
  at all. So the script 404'd, the LiveView socket was never opened, and every page was a
  single server-rendered snapshot with dead buttons. Nothing caught it, because
  `panel_test.exs` mounts LiveViews in-process — it never loads the document and so never
  asks for the script.

  ## Why a task rather than a build step

  There is no `assets/` directory, no npm, no esbuild, and this is the reason: the three
  libraries already ship built, minified UMD bundles that define globals, and the console
  needs nothing else. A build toolchain would be a second thing to install, a second
  thing for CI to cache and a second thing to go wrong, in exchange for concatenating
  three files that are already concatenated.

  Same shape as `mix troupe.admin.tokens`: generated, committed, and `--check` in CI so
  the committed bytes cannot drift from the dependency they came from.
  """

  use Mix.Task

  @output_path Path.join(~w(apps troupe_plane priv static app.js))

  # UMD builds, in dependency order: `phoenix` defines `Phoenix`, which
  # `phoenix_live_view` needs at load time.
  @sources [
    {:phoenix, ~w(priv static phoenix.min.js)},
    {:phoenix_html, ~w(priv static phoenix_html.js)},
    {:phoenix_live_view, ~w(priv static phoenix_live_view.min.js)}
  ]

  @impl Mix.Task
  def run(argv) do
    {opts, _rest, _invalid} = OptionParser.parse(argv, strict: [check: :boolean])

    js = build()

    if opts[:check] do
      check(js)
    else
      File.mkdir_p!(Path.dirname(@output_path))
      File.write!(@output_path, js)
      Mix.shell().info("wrote #{@output_path} (#{byte_size(js)} bytes)")
    end
  end

  defp check(js) do
    case File.read(@output_path) do
      {:ok, ^js} ->
        Mix.shell().info("app.js is current")

      {:ok, _stale} ->
        Mix.raise("""
        #{@output_path} does not match the vendored dependencies.

        Run `mix troupe.admin.assets` and commit the result. This usually means a Phoenix
        dependency moved and the panel is serving the JavaScript of the previous one.
        """)

      {:error, _reason} ->
        Mix.raise("#{@output_path} is missing: run `mix troupe.admin.assets`")
    end
  end

  defp build do
    versions =
      Enum.map_join(@sources, "\n", fn {app, _path} ->
        "   #{app} #{Application.spec(app, :vsn) || "?"}"
      end)

    header = """
    /* Generated by `mix troupe.admin.assets`. Do not edit.
       Vendored from:
    #{versions}
    */
    """

    bundles = Enum.map_join(@sources, "\n", &read_source/1)

    header <> bundles <> "\n" <> boot()
  end

  defp read_source({app, path}) do
    file = Path.join([Mix.Project.deps_path(), to_string(app) | path])

    case File.read(file) do
      {:ok, contents} ->
        ";/* #{app} */\n" <> contents

      {:error, reason} ->
        Mix.raise("cannot read #{file}: #{:file.format_error(reason)}")
    end
  end

  # The whole of the console's own JavaScript. It connects the socket and nothing else:
  # every behaviour on every page is server-rendered and patched, which is what lets the
  # design say the layout must not depend on measured width or client state.
  defp boot do
    """
    ;/* troupe console */
    (function () {
      "use strict";

      var csrf = document.querySelector("meta[name='csrf-token']");
      var socket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket, {
        params: { _csrf_token: csrf ? csrf.getAttribute("content") : null }
      });

      // The console-offline banner is `role="status"` in the markup and hidden until the
      // socket says otherwise. It is driven from here rather than from the server for the
      // obvious reason: when it matters, the server is the thing that cannot be reached.
      // The design is emphatic that values freeze and are timestamped rather than blanked,
      // so this only toggles an attribute — nothing is cleared.
      var root = document.documentElement;
      window.addEventListener("phx:page-loading-stop", function () {
        root.removeAttribute("data-console-offline");
      });
      socket.socket.onError(function () {
        root.setAttribute("data-console-offline", "true");
      });
      socket.socket.onOpen(function () {
        root.removeAttribute("data-console-offline");
      });

      socket.connect();
      window.liveSocket = socket;
    })();
    """
  end
end
