defmodule Mix.Tasks.Troupe.Admin.Tokens do
  @shortdoc "Generate the console's CSS custom properties from the design tokens"

  @moduledoc """
  Turn `docs/design/admin/tokens.json` into `apps/troupe_plane/priv/static/tokens.css`.

      mix troupe.admin.tokens
      mix troupe.admin.tokens --check

  The design document says every value in the console's stylesheet references a token.
  The way to make that true rather than aspirational is for the tokens to be the only
  place a colour is written down, and for the CSS to be generated from them — so a
  designer changing `tokens.json` changes the product, and a developer cannot quietly
  introduce a tenth status colour by typing a hex code into a stylesheet.

  `--check` regenerates into memory and fails if the committed file differs, which is
  what CI runs. Same shape as `mix troupe.schema.gen` and its check, for the same reason.

  ## The naming

  A variable's name is its path through the document with the leading `color.` dropped
  and the segments hyphenated: `color.bg.panel` becomes `--bg-panel`,
  `color.status.healthy.fg` becomes `--status-healthy-fg`, `density.rowHeight` becomes
  `--density-row-height`. Nothing is renamed by hand, so a token that is added appears
  in the CSS without anybody editing this file.

  Themed values — every `color.*` leaf carrying `dark` and `light` — are written twice:
  the dark value on `:root`, the light value under both `:root[data-theme="light"]` and
  a `prefers-color-scheme: light` block that an explicit dark choice overrides. Dark is
  the default because the design says it was designed first.
  """

  use Mix.Task

  @tokens_path Path.join(~w(docs design admin tokens.json))
  @output_path Path.join(~w(apps troupe_plane priv static tokens.css))

  # The status list, vendored into the app rather than read from `docs/` at compile time.
  # `Troupe.Plane.Web.Live.Status` needs the glyphs and words while it compiles, and the
  # image build copies `apps/`, `config/`, `mix.exs` and nothing else — so a module that
  # reached into the design directory compiled on a laptop and failed in Docker, which is
  # exactly what it did.
  @statuses_path Path.join(~w(apps troupe_plane priv design statuses.json))

  @impl Mix.Task
  def run(argv) do
    {opts, _rest, _invalid} = OptionParser.parse(argv, strict: [check: :boolean])

    tokens = read!(@tokens_path)
    css = render(tokens)
    statuses = statuses(tokens)

    if opts[:check] do
      check(@output_path, css)
      check(@statuses_path, statuses)
    else
      write(@output_path, css)
      write(@statuses_path, statuses)
    end
  end

  defp write(path, contents) do
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, contents)
    Mix.shell().info("wrote #{path} (#{byte_size(contents)} bytes)")
  end

  # Only what a renderer needs: the state, its glyph and its word. The colours are the
  # stylesheet's business and are already in `tokens.css`.
  defp statuses(tokens) do
    tokens
    |> get_in(["color", "status"])
    |> Enum.reject(fn {key, _value} -> meta?(key) end)
    |> Map.new(fn {state, value} ->
      {state, %{"glyph" => value["glyph"], "word" => value["word"]}}
    end)
    |> Jason.encode!(pretty: true)
    |> Kernel.<>("\n")
  end

  defp check(path, expected) do
    case File.read(path) do
      {:ok, ^expected} ->
        Mix.shell().info("#{Path.basename(path)} is current")

      {:ok, _stale} ->
        Mix.raise("#{path} is stale: run `mix troupe.admin.tokens` and commit it")

      {:error, _reason} ->
        Mix.raise("#{path} is missing: run `mix troupe.admin.tokens`")
    end
  end

  @doc false
  @spec read!(Path.t()) :: map()
  def read!(path) do
    case File.read(path) do
      {:ok, contents} -> Jason.decode!(contents)
      {:error, reason} -> Mix.raise("cannot read #{path}: #{:file.format_error(reason)}")
    end
  end

  @doc """
  The stylesheet for one token document.

  `:source` and `:task` name, in the header comment, where the values came from and what
  regenerates them: the same walk serves the console's token document and a theme kit's,
  and a reader who finds a stale value has to know which of the two to edit.
  """
  @spec render(map(), keyword()) :: String.t()
  def render(tokens, opts \\ []) do
    source = Keyword.get(opts, :source, @tokens_path)
    task = Keyword.get(opts, :task, "mix troupe.admin.tokens")
    {dark, light, plain} = collect(tokens)
    plain = plain ++ fonts(tokens)

    # Two tokens that generate the same variable is a value silently lost, which is how
    # `color.border.hairline` and `border.hairline` were one variable for a while.
    for bucket <- [plain ++ dark, light] do
      case bucket |> Enum.frequencies_by(&elem(&1, 0)) |> Enum.filter(&(elem(&1, 1) > 1)) do
        [] -> :ok
        clashes -> raise "tokens collide: #{inspect(Enum.map(clashes, &elem(&1, 0)))}"
      end
    end

    """
    /* Generated by `#{task}` from #{source}.
       Do not edit: change the tokens and regenerate. */

    :root {
    #{declarations(plain ++ dark)}
    }

    /* An explicit light choice, and the system preference where no choice was made.
       Written twice rather than once so that `data-theme="dark"` beats a light OS. */
    :root[data-theme="light"] {
    #{declarations(light)}
    }

    @media (prefers-color-scheme: light) {
      :root:not([data-theme="dark"]) {
    #{declarations(light, "    ")}
      }
    }
    """
  end

  # The design's type table is role to font, and CSS has a shorthand for exactly that.
  # Composed here rather than left to the stylesheet so a role is one token, and so five
  # parts cannot be recombined differently on two different pages.
  defp fonts(tokens) do
    families = get_in(tokens, ["typography", "family"]) || %{}

    tokens
    |> get_in(["typography", "role"])
    |> Kernel.||(%{})
    |> Enum.reject(fn {key, _value} -> meta?(key) end)
    |> Enum.sort()
    |> Enum.map(fn {role, spec} ->
      family = unwrap(Map.get(families, spec["family"], spec["family"]))
      weight = unwrap(spec["weight"])
      size = unwrap(spec["size"])
      height = unwrap(spec["lineHeight"])
      {var(["typography", "role", role]), "#{weight} #{size}/#{height} #{family}"}
    end)
  end

  # A token is sometimes the value and sometimes `{value, description}`; both shapes
  # appear in the document and both mean the same thing to a stylesheet.
  defp unwrap(%{"value" => value}), do: value
  defp unwrap(value), do: value

  defp declarations(pairs, indent \\ "  ") do
    Enum.map_join(pairs, "\n", fn {name, value} -> "#{indent}#{name}: #{value};" end)
  end

  # Walks the document once, sorting every leaf into three buckets: the dark half of a
  # themed value, the light half, and everything that is the same in both.
  defp collect(tokens) do
    tokens
    |> Enum.reject(fn {key, _value} -> meta?(key) end)
    |> Enum.reduce({[], [], []}, fn {group, value}, acc ->
      walk(value, prefix(group), acc)
    end)
    |> then(fn {dark, light, plain} ->
      {Enum.reverse(dark), Enum.reverse(light), Enum.reverse(plain)}
    end)
  end

  # A map carrying both `dark` and `light` is one themed value, not two nested ones.
  defp walk(%{"dark" => dark, "light" => light}, path, {d, l, p}) do
    {[{var(path), dark} | d], [{var(path), light} | l], p}
  end

  defp walk(%{} = map, path, acc) do
    map
    |> Enum.reject(fn {key, _value} -> meta?(key) end)
    |> Enum.reduce(acc, fn {key, value}, inner -> walk(value, path ++ [key], inner) end)
  end

  defp walk(value, path, {d, l, p} = acc) when is_binary(value) or is_number(value) do
    if annotation?(path), do: acc, else: {d, l, [{var(path), quoted(path, value)} | p]}
  end

  # Lists are documentation — a theme list, a set of rules — and describe the system
  # rather than being a value any rule can use.
  defp walk(_other, _path, acc), do: acc

  # `$meta`, `$note`, `$shape`: prose about the system, addressed to a reader.
  defp meta?(key), do: String.starts_with?(key, "$")

  # Descriptions and measured contrast ratios document a token for a reader; they are
  # prose about the system rather than anything a rule can use, so a leaf whose last
  # segment is one of these is dropped rather than emitted as a value.
  @annotations ~w(description contrastOnPanel contrastOnCanvas note use)

  defp annotation?(path), do: List.last(path) in @annotations

  # A glyph and a status word are values a rule genuinely uses — `content: var(--…)` for
  # the glyph — and both can contain a space or a character CSS would not accept bare.
  @quoted ~w(glyph word)

  defp quoted(path, value) do
    if List.last(path) in @quoted, do: ~s("#{value}"), else: value
  end

  # No group is dropped. `color.border.hairline` is a colour and `border.hairline` is a
  # width; dropping the `color.` prefix made them one variable, and whichever the walk
  # reached last silently won.
  defp prefix(group), do: [group]

  defp var(path) do
    path
    |> trim_value()
    |> Enum.map_join("-", &hyphenate/1)
    |> then(&("--" <> &1))
  end

  # `breakpoint.lg.value` is the breakpoint; the segment carries no meaning of its own.
  defp trim_value(path) do
    case Enum.reverse(path) do
      ["value" | rest] when rest != [] -> Enum.reverse(rest)
      _other -> path
    end
  end

  # `rowHeight` becomes `row-height`, so a name in CSS reads the way CSS names read.
  defp hyphenate(segment) do
    segment
    |> String.replace(~r/([a-z0-9])([A-Z])/, "\\1-\\2")
    |> String.downcase()
  end
end
