defmodule Troupe.Plane.FrontPageAssetsTest do
  @moduledoc """
  The front page asks for files and obeys one rule about colour; both are checked here.

  Sibling of `console_assets_test.exs`, and for the same reason it exists: nothing else
  checks the contract between a document and the file system. `web_test.exs` fetches `/`
  over a socket, but it mounts the bare `Router` — the static plug lives on the
  `Endpoint`, so a stylesheet the page names and the endpoint does not serve would pass
  every test in that file and render as unstyled HTML in front of whoever was handed the
  plane's URL.

  The colour rule is the other half. `docs/design/themes/THEMES.md` reserves one hue per
  theme — magenta in Signal — for a single meaning: *stopped, a person must decide*. A
  page that spends it on a heading or a button spends the meaning too, and the loss is
  invisible until somebody misses a real approval. So the front page's use of it is
  pinned to one place, and the inline stylesheet is checked for colours of its own.
  """

  use ExUnit.Case, async: true

  alias Troupe.Plane.Web.Endpoint
  alias Troupe.Plane.Web.Index

  @static_root Application.app_dir(:troupe_plane, "priv/static")
  @endpoint_source Path.join(__DIR__, "../../../lib/troupe/plane/web/endpoint.ex")

  defp document do
    Index.render(name: "a plane", url: "https://plane.example.test", app_url: "/app")
  end

  # `/static/brand/favicon.svg` is the reference; `brand/favicon.svg` is the path under
  # `priv/static`. The `og:image` names the same file absolutely, hence the dedup.
  defp referenced_assets do
    ~r{/static/(?<file>[A-Za-z0-9._-]+(?:/[A-Za-z0-9._-]+)*)}
    |> Regex.scan(document(), capture: ["file"])
    |> List.flatten()
    |> Enum.uniq()
  end

  defp allowlist(at) do
    source = File.read!(@endpoint_source)
    [_all, allowed] = Regex.run(~r/at: "#{at}",.*?only: ~w\(([^)]+)\)/s, source)
    String.split(allowed, ~r/\s+/, trim: true)
  end

  test "the page names the theme, the mask and every icon format a browser asks for" do
    assets = referenced_assets()

    assert "theme.css" in assets
    assert "brand/mask.png" in assets, "the front page is the photograph of the mask"
    assert "brand/favicon.svg" in assets
    assert "brand/favicon.ico" in assets, "an SVG favicon alone leaves older clients blank"
    assert "brand/apple-touch-icon.png" in assets
  end

  test "every asset the page names exists on disk and is not empty" do
    for asset <- referenced_assets() do
      path = Path.join(@static_root, asset)

      assert File.exists?(path), """
      The front page references /static/#{asset} and there is no such file.

      `theme.css` is generated by `mix troupe.theme` from the Signal kit; the files under
      `brand/` are authored by hand, apart from the two bitmaps `scripts/brand-icons.py`
      rasterises. All of them are committed.
      """

      assert File.stat!(path).size > 0, "#{asset} is empty"
    end
  end

  test "every asset the page names is in the front page's static allowlist" do
    # Read from the source rather than the endpoint's compiled plug list: the compiled
    # list would be testing Plug, and the source is the thing that goes wrong.
    allowed = allowlist("/static")

    for asset <- referenced_assets() do
      root = asset |> Path.split() |> hd()

      assert root in allowed, """
      /static/#{asset} is referenced by the page but `#{root}` is not in the static plug's
      `only:` list, so it is served as a 404 however present the file is.

      Allowed: #{inspect(allowed)}
      """
    end
  end

  test "the two static mounts stay separate" do
    # The console's own allowlist is checked by `console_assets_test.exs`; what matters
    # here is that adding the front page's mount did not fold the two together. A single
    # mount would mean the front page's stylesheet is only reachable behind `/admin`.
    assert allowlist("/admin/static") == ~w(app.js tokens.css console.css)
    refute "theme.css" in allowlist("/admin/static")
  end

  # The allowlist checks above read the source. This one runs the real pipeline, which is
  # the only way to find out that a mount answers — `web_test.exs` cannot, because it
  # starts the bare `Router` and the static plugs are on the `Endpoint`.
  test "the endpoint actually serves what the page asks for" do
    for asset <- referenced_assets() do
      conn = Endpoint.call(Plug.Test.conn(:get, "/static/" <> asset), [])

      assert conn.status == 200, "GET /static/#{asset} answered #{conn.status}"

      # `Plug.Static` answers with `send_file`, which leaves the conn in `:file` rather
      # than `:sent`; what matters is that it answered at all, rather than falling
      # through to the router's 404.
      assert conn.state in [:file, :sent]
    end
  end

  test "a file outside the allowlist is not served just because it is in priv/static" do
    conn = Endpoint.call(Plug.Test.conn(:get, "/static/app.js"), [])

    refute conn.status == 200
  end

  describe "the stylesheet against the theme" do
    @theme File.read!(Path.join(@static_root, "theme.css"))

    test "theme.css is the Signal kit, generated rather than written" do
      assert @theme =~ "Generated by `mix troupe.theme`"
      assert @theme =~ "docs/design/themes/signal.tokens.json"
    end

    test "every custom property the page uses is defined by the generated theme" do
      defined =
        ~r/^\s*(--[a-zA-Z0-9-]+)\s*:/m
        |> Regex.scan(@theme, capture: :all_but_first)
        |> List.flatten()
        |> MapSet.new()

      used =
        ~r/var\((--[a-zA-Z0-9-]+)\)/
        |> Regex.scan(document(), capture: :all_but_first)
        |> List.flatten()
        |> MapSet.new()

      missing = MapSet.difference(used, defined)

      assert MapSet.size(missing) == 0, """
      The front page uses custom properties the theme does not define, so those rules
      silently do nothing:

      #{missing |> MapSet.to_list() |> Enum.sort() |> Enum.join("\n")}
      """
    end

    test "the page contains no colour of its own" do
      hexes = ~r/#[0-9a-fA-F]{3,8}\b/ |> Regex.scan(document()) |> List.flatten()

      assert hexes == [], """
      #{length(hexes)} literal colour(s) on the front page: #{inspect(Enum.uniq(hexes))}

      Change `docs/design/themes/signal.tokens.json` and run `mix troupe.theme` instead.
      """
    end
  end

  describe "the reserved colour" do
    test "magenta is spent once, on the mask, and nowhere else" do
      uses =
        ~r/var\(--color-status-waiting-solid\)/
        |> Regex.scan(document())
        |> length()

      assert uses == 1, """
      The reserved colour appears #{uses} times on the front page. It means one thing —
      stopped, a person must decide — and the front page's one licensed use of it is the
      filled half of the mask. Anything else spends the meaning.
      """
    end

    test "the one use is inside the mark" do
      [_all, mark] = Regex.run(~r|(<svg class="mark".*?</svg>)|s, document())

      assert mark =~ "var(--color-status-waiting-solid)"
      # The kit drops the seam line below 32px and flattens the eyes below 24px; this
      # mark is 20px, so it is the small geometry at the heavy stroke.
      assert mark =~ ~s(width="20")
      assert mark =~ ~s(stroke-width="3.4")
      refute mark =~ "M24 8 L24 42", "the seam line does not belong under 32px"
    end
  end
end
