# Generated from clients/gui/docs/design/themes/afterglow.tokens.json by
# `mix troupe.palette`. Do not edit by hand: change the tokens, or the role table in
# lib/mix/tasks/troupe.palette.ex, and run it again. `mix troupe.palette --check`
# fails when this file is not what they say.
defmodule Troupe.UI.TUI.Palette do
  @moduledoc """
  Troupe — Afterglow, for a terminal: every colour the TUI draws, by role, and the mask.

  `Troupe.UI.TUI.Theme` chooses from this what a terminal can show. Generated by
  `mix troupe.palette`; see that task for what each part is.
  """

  @typedoc "What a colour is for. The view names a role, never a colour."
  @type role ::
          :needs_you
          | :needs_you_edge
          | :brand
          | :working
          | :working_edge
          | :accent
          | :ok
          | :error
          | :offline
          | :added
          | :removed
          | :hunk
          | :muted
          | :rail

  @typedoc "A pixel of the mask: `?o` edge, `?f` lit half, `?e` solid eye, `?c` cut eye, `?.` none."
  @type mask :: [String.t()]

  @roles %{
    # a person is needed: an approval, a question, the budget question, the window and status that say so
    needs_you: %{
      token: "status.waiting.fg",
      dark: %{rgb: {255, 0, 128}, x256: 198},
      light: %{rgb: {196, 0, 95}, x256: 161},
      x16: :magenta
    },
    # the border of a window that needs you
    needs_you_edge: %{
      token: "status.waiting.border",
      dark: %{rgb: {255, 0, 128}, x256: 198},
      light: %{rgb: {196, 0, 95}, x256: 161},
      x16: :magenta
    },
    # the mask's lit half, the one use of the reserved colour that is not a request
    brand: %{
      token: "status.waiting.solid",
      dark: %{rgb: {255, 0, 128}, x256: 198},
      light: %{rgb: {196, 0, 95}, x256: 161},
      x16: :magenta
    },
    # the machine working: the activity line, a running tool
    working: %{
      token: "status.running.fg",
      dark: %{rgb: {0, 219, 211}, x256: 44},
      light: %{rgb: {0, 100, 102}, x256: 23},
      x16: :cyan
    },
    # the border of a window that is working
    working_edge: %{
      token: "status.running.border",
      dark: %{rgb: {0, 134, 135}, x256: 30},
      light: %{rgb: {79, 176, 177}, x256: 73},
      x16: :cyan
    },
    # the light that is not a status: headings, bullets, code labels, your marker, the selected row
    accent: %{
      token: "border.focus",
      dark: %{rgb: {0, 198, 201}, x256: 44},
      light: %{rgb: {0, 122, 124}, x256: 30},
      x16: :cyan
    },
    # a tool that succeeded, a window done and not yet read
    ok: %{
      token: "status.allowed.fg",
      dark: %{rgb: {0, 219, 211}, x256: 44},
      light: %{rgb: {0, 100, 102}, x256: 23},
      x16: :green
    },
    # a tool that failed, a window that failed
    error: %{
      token: "status.error.fg",
      dark: %{rgb: {255, 106, 85}, x256: 203},
      light: %{rgb: {165, 38, 26}, x256: 88},
      x16: :red
    },
    # a plane that does not answer
    offline: %{
      token: "status.offline.fg",
      dark: %{rgb: {201, 178, 122}, x256: 180},
      light: %{rgb: {93, 74, 30}, x256: 58},
      x16: :yellow
    },
    # a line a diff adds
    added: %{
      token: "diff.addedText",
      dark: %{rgb: {0, 219, 211}, x256: 44},
      light: %{rgb: {0, 100, 102}, x256: 23},
      x16: :green
    },
    # a line a diff removes
    removed: %{
      token: "diff.removedText",
      dark: %{rgb: {255, 126, 110}, x256: 210},
      light: %{rgb: {142, 47, 31}, x256: 88},
      x16: :red
    },
    # a diff's file and hunk headers
    hunk: %{
      token: "diff.hunkHeader",
      dark: %{rgb: {138, 138, 160}, x256: 103},
      light: %{rgb: {90, 90, 118}, x256: 60},
      x16: :dark_gray
    },
    # what is there to be read second: the status line, greyed rows, reasoning, tool notes
    muted: %{
      token: "text.muted",
      dark: %{rgb: {123, 123, 148}, x256: 103},
      light: %{rgb: {95, 95, 120}, x256: 60},
      x16: :dark_gray
    },
    # code and quote rails, line numbers, the scrollbar, an unfocused box
    rail: %{
      token: "border.strong",
      dark: %{rgb: {104, 100, 98}, x256: 241},
      light: %{rgb: {146, 142, 135}, x256: 245},
      x16: :dark_gray
    }
  }

  @doc "Every role: its token, dark and light values with their xterm-256 nearest, and its stand-in among the sixteen."
  @spec roles() :: %{role() => map()}
  def roles, do: @roles

  @doc "The mask at a cut: `:large` is 16 cells wide, `:small` 10."
  @spec mask(:large | :small) :: mask()
  def mask(:large),
    do: [
      "...oooooooooo...",
      "..oooooooooooo..",
      ".oo.....fffffoo.",
      "oo......ffffffoo",
      "oo......ffffffoo",
      "oo......ffffffoo",
      "oo......ffffffoo",
      "oo..eee.fcccffoo",
      "oo......ffffffoo",
      "oo......ffffffoo",
      "oo......ffffffoo",
      "oo......ffffffoo",
      ".oo.....fffffoo.",
      ".oo.....fffffoo.",
      "..oo....ffffoo..",
      "...ooo..ffooo...",
      "....ooo.fooo....",
      ".....oooooo.....",
      ".......oo.......",
      "................"
    ]

  def mask(:small),
    do: [
      "..oooooo..",
      "ooo..ffooo",
      "o....ffffo",
      "o....ffffo",
      "o..e.fcffo",
      "o....ffffo",
      "o....ffffo",
      "o....ffffo",
      ".o...fffo.",
      ".oo..ffoo.",
      "...oooo...",
      "....oo...."
    ]
end
