# Generated from clients/gui/docs/design/themes/
#   afterglow.tokens.json
#   signal.tokens.json
#   footlight.tokens.json
#   limelight.tokens.json
# by `mix troupe.palette`. Do not edit by hand: change the tokens, or the role table in
# lib/mix/tasks/troupe.palette.ex, and run it again. `mix troupe.palette --check`
# fails when this file is not what they say.
defmodule Troupe.UI.TUI.Palette do
  @moduledoc """
  The themes for a terminal — Afterglow, Signal, Footlight, Limelight: every colour the TUI
  draws, by role, in each theme, and the mask.

  `Troupe.UI.TUI.Theme` chooses from this what a terminal can show. Generated by
  `mix troupe.palette`; see that task for what each part is.
  """

  @typedoc "A theme, by the id its tokens file gives it."
  @type theme :: :afterglow | :signal | :footlight | :limelight

  @typedoc """
  What a colour is for. The view names a role, never a colour:

    * `:needs_you` — a person is needed: an approval, a question, the budget question, the window and status that say so
    * `:needs_you_edge` — the border of a window that needs you
    * `:brand` — the mask's lit half, the one use of the reserved colour that is not a request
    * `:working` — the machine working: the activity line, a running tool
    * `:working_edge` — the border of a window that is working
    * `:accent` — the light that is not a status: headings, bullets, code labels, your marker, the selected row
    * `:ok` — a tool that succeeded, a window done and not yet read
    * `:error` — a tool that failed, a window that failed
    * `:offline` — a plane that does not answer
    * `:stale` — a fact that may no longer be true: an anchor of it changed or went
    * `:added` — a line a diff adds
    * `:removed` — a line a diff removes
    * `:hunk` — a diff's file and hunk headers
    * `:muted` — what is there to be read second: the status line, greyed rows, reasoning, tool notes
    * `:rail` — code and quote rails, line numbers, the scrollbar, an unfocused box
  """
  @type role ::
          :needs_you
          | :needs_you_edge
          | :brand
          | :working
          | :working_edge
          | :accent
          | :ok
          | :error
          | :offline
          | :stale
          | :added
          | :removed
          | :hunk
          | :muted
          | :rail

  @typedoc "A pixel of the mask: `?o` edge, `?f` lit half, `?e` solid eye, `?c` cut eye, `?.` none."
  @type mask :: [String.t()]

  @themes [
    %{
      id: :afterglow,
      name: "Afterglow",
      description:
        "Void and pit under cream, and two lights on it: pink is you being asked, cyan is the machine working. The stage after the house lights go down.",
      reserved: "pink"
    },
    %{
      id: :signal,
      name: "Signal",
      description:
        "Neutral graphite with no blue cast, and a printer's duotone on top: cyan is the machine working, magenta is you being asked.",
      reserved: "magenta"
    },
    %{
      id: :footlight,
      name: "Footlight",
      description:
        "Ink navy, drafting blue-grey, one stage amber. The default theme: cool, quiet infrastructure with a single warm light in it.",
      reserved: "stage amber"
    },
    %{
      id: :limelight,
      name: "Limelight",
      description:
        "Warm ink grounds — smoked oak and auditorium dark — with attention carried by limelight, the pale greenish-white of burning quicklime.",
      reserved: "limelight"
    }
  ]

  @roles %{
    afterglow: %{
      needs_you: %{
        token: "status.waiting.fg",
        dark: %{rgb: {255, 0, 128}, x256: 198},
        light: %{rgb: {196, 0, 95}, x256: 161},
        x16: :magenta
      },
      needs_you_edge: %{
        token: "status.waiting.border",
        dark: %{rgb: {255, 0, 128}, x256: 198},
        light: %{rgb: {196, 0, 95}, x256: 161},
        x16: :magenta
      },
      brand: %{
        token: "status.waiting.solid",
        dark: %{rgb: {255, 0, 128}, x256: 198},
        light: %{rgb: {196, 0, 95}, x256: 161},
        x16: :magenta
      },
      working: %{
        token: "status.running.fg",
        dark: %{rgb: {0, 219, 211}, x256: 44},
        light: %{rgb: {0, 100, 102}, x256: 23},
        x16: :cyan
      },
      working_edge: %{
        token: "status.running.border",
        dark: %{rgb: {0, 134, 135}, x256: 30},
        light: %{rgb: {79, 176, 177}, x256: 73},
        x16: :cyan
      },
      accent: %{
        token: "border.focus",
        dark: %{rgb: {0, 198, 201}, x256: 44},
        light: %{rgb: {0, 122, 124}, x256: 30},
        x16: :cyan
      },
      ok: %{
        token: "status.allowed.fg",
        dark: %{rgb: {0, 219, 211}, x256: 44},
        light: %{rgb: {0, 100, 102}, x256: 23},
        x16: :green
      },
      error: %{
        token: "status.error.fg",
        dark: %{rgb: {255, 106, 85}, x256: 203},
        light: %{rgb: {165, 38, 26}, x256: 88},
        x16: :red
      },
      offline: %{
        token: "status.offline.fg",
        dark: %{rgb: {201, 178, 122}, x256: 180},
        light: %{rgb: {93, 74, 30}, x256: 58},
        x16: :yellow
      },
      stale: %{
        token: "status.offline.fg",
        dark: %{rgb: {201, 178, 122}, x256: 180},
        light: %{rgb: {93, 74, 30}, x256: 58},
        x16: :yellow
      },
      added: %{
        token: "diff.addedText",
        dark: %{rgb: {0, 219, 211}, x256: 44},
        light: %{rgb: {0, 100, 102}, x256: 23},
        x16: :green
      },
      removed: %{
        token: "diff.removedText",
        dark: %{rgb: {255, 126, 110}, x256: 210},
        light: %{rgb: {142, 47, 31}, x256: 88},
        x16: :red
      },
      hunk: %{
        token: "diff.hunkHeader",
        dark: %{rgb: {138, 138, 160}, x256: 103},
        light: %{rgb: {90, 90, 118}, x256: 60},
        x16: :dark_gray
      },
      muted: %{
        token: "text.muted",
        dark: %{rgb: {123, 123, 148}, x256: 103},
        light: %{rgb: {95, 95, 120}, x256: 60},
        x16: :dark_gray
      },
      rail: %{
        token: "border.strong",
        dark: %{rgb: {104, 100, 98}, x256: 241},
        light: %{rgb: {146, 142, 135}, x256: 245},
        x16: :dark_gray
      }
    },
    signal: %{
      needs_you: %{
        token: "status.waiting.fg",
        dark: %{rgb: {255, 127, 198}, x256: 212},
        light: %{rgb: {155, 10, 94}, x256: 125},
        x16: :magenta
      },
      needs_you_edge: %{
        token: "status.waiting.border",
        dark: %{rgb: {138, 33, 96}, x256: 89},
        light: %{rgb: {230, 139, 192}, x256: 175},
        x16: :magenta
      },
      brand: %{
        token: "status.waiting.solid",
        dark: %{rgb: {255, 92, 184}, x256: 205},
        light: %{rgb: {193, 26, 121}, x256: 125},
        x16: :magenta
      },
      working: %{
        token: "status.running.fg",
        dark: %{rgb: {63, 210, 232}, x256: 45},
        light: %{rgb: {10, 88, 102}, x256: 23},
        x16: :cyan
      },
      working_edge: %{
        token: "status.running.border",
        dark: %{rgb: {18, 91, 105}, x256: 23},
        light: %{rgb: {133, 196, 207}, x256: 116},
        x16: :cyan
      },
      accent: %{
        token: "border.focus",
        dark: %{rgb: {63, 210, 232}, x256: 45},
        light: %{rgb: {10, 88, 102}, x256: 23},
        x16: :cyan
      },
      ok: %{
        token: "status.allowed.fg",
        dark: %{rgb: {95, 214, 155}, x256: 79},
        light: %{rgb: {15, 99, 66}, x256: 29},
        x16: :green
      },
      error: %{
        token: "status.error.fg",
        dark: %{rgb: {255, 107, 91}, x256: 203},
        light: %{rgb: {163, 32, 15}, x256: 88},
        x16: :red
      },
      offline: %{
        token: "status.offline.fg",
        dark: %{rgb: {201, 178, 122}, x256: 180},
        light: %{rgb: {93, 74, 30}, x256: 58},
        x16: :yellow
      },
      stale: %{
        token: "status.offline.fg",
        dark: %{rgb: {201, 178, 122}, x256: 180},
        light: %{rgb: {93, 74, 30}, x256: 58},
        x16: :yellow
      },
      added: %{
        token: "diff.addedText",
        dark: %{rgb: {127, 220, 174}, x256: 115},
        light: %{rgb: {11, 86, 55}, x256: 23},
        x16: :green
      },
      removed: %{
        token: "diff.removedText",
        dark: %{rgb: {239, 162, 148}, x256: 217},
        light: %{rgb: {131, 46, 30}, x256: 52},
        x16: :red
      },
      hunk: %{
        token: "diff.hunkHeader",
        dark: %{rgb: {125, 132, 142}, x256: 244},
        light: %{rgb: {82, 90, 100}, x256: 240},
        x16: :dark_gray
      },
      muted: %{
        token: "text.muted",
        dark: %{rgb: {125, 132, 142}, x256: 244},
        light: %{rgb: {88, 95, 104}, x256: 59},
        x16: :dark_gray
      },
      rail: %{
        token: "border.strong",
        dark: %{rgb: {58, 66, 76}, x256: 238},
        light: %{rgb: {151, 158, 167}, x256: 247},
        x16: :dark_gray
      }
    },
    footlight: %{
      needs_you: %{
        token: "status.waiting.fg",
        dark: %{rgb: {255, 180, 61}, x256: 214},
        light: %{rgb: {122, 74, 0}, x256: 94},
        x16: :magenta
      },
      needs_you_edge: %{
        token: "status.waiting.border",
        dark: %{rgb: {138, 94, 18}, x256: 94},
        light: %{rgb: {216, 151, 34}, x256: 172},
        x16: :magenta
      },
      brand: %{
        token: "status.waiting.solid",
        dark: %{rgb: {255, 180, 61}, x256: 214},
        light: %{rgb: {179, 106, 0}, x256: 130},
        x16: :magenta
      },
      working: %{
        token: "status.running.fg",
        dark: %{rgb: {79, 207, 176}, x256: 79},
        light: %{rgb: {4, 107, 87}, x256: 23},
        x16: :cyan
      },
      working_edge: %{
        token: "status.running.border",
        dark: %{rgb: {28, 91, 78}, x256: 23},
        light: %{rgb: {143, 205, 190}, x256: 116},
        x16: :cyan
      },
      accent: %{
        token: "border.focus",
        dark: %{rgb: {140, 192, 240}, x256: 110},
        light: %{rgb: {15, 76, 129}, x256: 24},
        x16: :cyan
      },
      ok: %{
        token: "status.allowed.fg",
        dark: %{rgb: {107, 208, 140}, x256: 78},
        light: %{rgb: {17, 107, 51}, x256: 29},
        x16: :green
      },
      error: %{
        token: "status.error.fg",
        dark: %{rgb: {255, 126, 110}, x256: 210},
        light: %{rgb: {163, 34, 19}, x256: 88},
        x16: :red
      },
      offline: %{
        token: "status.offline.fg",
        dark: %{rgb: {198, 176, 138}, x256: 180},
        light: %{rgb: {95, 74, 33}, x256: 58},
        x16: :yellow
      },
      stale: %{
        token: "status.offline.fg",
        dark: %{rgb: {198, 176, 138}, x256: 180},
        light: %{rgb: {95, 74, 33}, x256: 58},
        x16: :yellow
      },
      added: %{
        token: "diff.addedText",
        dark: %{rgb: {143, 224, 172}, x256: 115},
        light: %{rgb: {14, 92, 44}, x256: 29},
        x16: :green
      },
      removed: %{
        token: "diff.removedText",
        dark: %{rgb: {245, 167, 154}, x256: 217},
        light: %{rgb: {140, 44, 24}, x256: 88},
        x16: :red
      },
      hunk: %{
        token: "diff.hunkHeader",
        dark: %{rgb: {126, 143, 162}, x256: 245},
        light: %{rgb: {85, 100, 122}, x256: 60},
        x16: :dark_gray
      },
      muted: %{
        token: "text.muted",
        dark: %{rgb: {126, 143, 162}, x256: 245},
        light: %{rgb: {92, 107, 122}, x256: 242},
        x16: :dark_gray
      },
      rail: %{
        token: "border.strong",
        dark: %{rgb: {54, 72, 93}, x256: 238},
        light: %{rgb: {152, 167, 182}, x256: 248},
        x16: :dark_gray
      }
    },
    limelight: %{
      needs_you: %{
        token: "status.waiting.fg",
        dark: %{rgb: {220, 244, 112}, x256: 192},
        light: %{rgb: {69, 79, 5}, x256: 58},
        x16: :magenta
      },
      needs_you_edge: %{
        token: "status.waiting.border",
        dark: %{rgb: {101, 120, 26}, x256: 58},
        light: %{rgb: {168, 188, 60}, x256: 149},
        x16: :magenta
      },
      brand: %{
        token: "status.waiting.solid",
        dark: %{rgb: {203, 234, 92}, x256: 191},
        light: %{rgb: {110, 127, 18}, x256: 100},
        x16: :magenta
      },
      working: %{
        token: "status.running.fg",
        dark: %{rgb: {116, 188, 202}, x256: 73},
        light: %{rgb: {20, 86, 95}, x256: 23},
        x16: :cyan
      },
      working_edge: %{
        token: "status.running.border",
        dark: %{rgb: {33, 80, 88}, x256: 23},
        light: %{rgb: {138, 192, 200}, x256: 109},
        x16: :cyan
      },
      accent: %{
        token: "text.link",
        dark: %{rgb: {147, 183, 224}, x256: 110},
        light: %{rgb: {31, 79, 134}, x256: 24},
        x16: :cyan
      },
      ok: %{
        token: "status.allowed.fg",
        dark: %{rgb: {169, 196, 140}, x256: 151},
        light: %{rgb: {59, 88, 32}, x256: 65},
        x16: :green
      },
      error: %{
        token: "status.error.fg",
        dark: %{rgb: {255, 124, 94}, x256: 209},
        light: %{rgb: {158, 32, 16}, x256: 88},
        x16: :red
      },
      offline: %{
        token: "status.offline.fg",
        dark: %{rgb: {203, 171, 112}, x256: 180},
        light: %{rgb: {92, 72, 24}, x256: 94},
        x16: :yellow
      },
      stale: %{
        token: "status.offline.fg",
        dark: %{rgb: {203, 171, 112}, x256: 180},
        light: %{rgb: {92, 72, 24}, x256: 94},
        x16: :yellow
      },
      added: %{
        token: "diff.addedText",
        dark: %{rgb: {182, 216, 152}, x256: 150},
        light: %{rgb: {49, 80, 26}, x256: 22},
        x16: :green
      },
      removed: %{
        token: "diff.removedText",
        dark: %{rgb: {239, 161, 131}, x256: 216},
        light: %{rgb: {126, 47, 20}, x256: 52},
        x16: :red
      },
      hunk: %{
        token: "diff.hunkHeader",
        dark: %{rgb: {141, 134, 115}, x256: 102},
        light: %{rgb: {92, 86, 68}, x256: 240},
        x16: :dark_gray
      },
      muted: %{
        token: "text.muted",
        dark: %{rgb: {141, 134, 115}, x256: 102},
        light: %{rgb: {97, 91, 74}, x256: 240},
        x16: :dark_gray
      },
      rail: %{
        token: "border.strong",
        dark: %{rgb: {74, 69, 52}, x256: 238},
        light: %{rgb: {154, 146, 124}, x256: 101},
        x16: :dark_gray
      }
    }
  }

  @doc "Every theme, in the order the desktop app offers them; the first is the default."
  @spec themes() :: [
          %{id: theme(), name: String.t(), description: String.t(), reserved: String.t()}
        ]
  def themes, do: @themes

  @doc "A theme's roles: each one's token, dark and light values with their xterm-256 nearest, and its stand-in among the sixteen."
  @spec roles(theme()) :: %{role() => map()}
  def roles(theme \\ :afterglow), do: Map.fetch!(@roles, theme)

  @doc "The mask at a cut: `:large` is 16 cells wide, `:small` 10."
  @spec mask(:large | :small) :: mask()
  def mask(:large),
    do: [
      "...oooooooooo...",
      "..oooooooooooo..",
      ".oo.....fffffoo.",
      "oo......ffffffoo",
      "oo......ffffffoo",
      "oo......ffffffoo",
      "oo......ffffffoo",
      "oo..eee.fcccffoo",
      "oo......ffffffoo",
      "oo......ffffffoo",
      "oo......ffffffoo",
      "oo......ffffffoo",
      ".oo.....fffffoo.",
      ".oo.....fffffoo.",
      "..oo....ffffoo..",
      "...ooo..ffooo...",
      "....ooo.fooo....",
      ".....oooooo.....",
      ".......oo.......",
      "................"
    ]

  def mask(:small),
    do: [
      "..oooooo..",
      "ooo..ffooo",
      "o....ffffo",
      "o....ffffo",
      "o..e.fcffo",
      "o....ffffo",
      "o....ffffo",
      "o....ffffo",
      ".o...fffo.",
      ".oo..ffoo.",
      "...oooo...",
      "....oo...."
    ]
end
