defmodule Mix.Tasks.Troupe.Egress do
  @shortdoc "Generate the egress allowlist from what each component declares it dials"

  @moduledoc """
  Write `docs/egress-allowlist.md` from `Troupe.Egress`.

      mix troupe.egress
      mix troupe.egress --check

  ## Why generated

  An allowlist written by hand is a list of what somebody remembered, and the failure it
  produces is the expensive kind: a NetworkPolicy that looks complete and refuses one host
  at the moment somebody first needs it. Generated from the declarations, the document
  cannot be more optimistic than the code.

  `--check` in CI, the same shape as `mix troupe.admin.assets --check` and
  `mix troupe.admin.tokens --check`: the committed bytes cannot drift from what they are
  generated from.
  """

  use Mix.Task

  alias Troupe.Egress

  @output Path.join(~w(docs egress-allowlist.md))

  @impl Mix.Task
  def run(argv) do
    {opts, _rest, _invalid} = OptionParser.parse(argv, strict: [check: :boolean])

    document = render()

    if opts[:check] do
      check(document)
    else
      File.mkdir_p!(Path.dirname(@output))
      File.write!(@output, document)
      Mix.shell().info("wrote #{@output} (#{length(Egress.entries())} declarations)")
    end
  end

  defp check(document) do
    case File.read(@output) do
      {:ok, ^document} ->
        Mix.shell().info("#{@output} is current")

      {:ok, _stale} ->
        Mix.raise("""
        #{@output} does not match `Troupe.Egress`.

        Run `mix troupe.egress` and commit the result. The document is generated so that it
        cannot claim less than the code reaches for.
        """)

      {:error, _reason} ->
        Mix.raise("#{@output} is missing: run `mix troupe.egress`")
    end
  end

  defp render do
    """
    # What Troupe dials

    <!-- Generated by `mix troupe.egress`. Do not edit: the declarations are in
         `Troupe.Egress`, and this document is written from them so it cannot claim less
         than the code reaches for. -->

    Every host this product connects to, declared by the component that connects to it.
    Three kinds, and the difference is what an operator needs:

    * **in the source** — a hostname the code has. A deployment that allows nothing else
      still has to allow these, and the chart's `troupePolicy.allowedEgress` defaults are
      checked against them.
    * **named by a setting** — somebody's own identity provider, database, bucket or key
      manager. The declaration is *which setting names it*, because the host is yours.
    * **the reader's browser** — fetched by a browser looking at the console, never by a
      pod. No NetworkPolicy governs these and an allowlist that omitted them would send
      somebody hunting a cluster rule for a request no pod makes.

    #{sections()}
    ## What is not here

    Anything a profile names. `egress.fqdns` and `egress.gitHosts` are a platform admin's
    decision per profile, checked against the policy when a bundle is published and again
    at admission. They are listed on the console's Integrations screen, with the cluster
    policy's verdict on each — which is the per-deployment answer this document cannot be.
    """
  end

  defp sections do
    Egress.components()
    |> Enum.map_join("\n", fn component ->
      rows =
        Egress.entries()
        |> Enum.filter(&(&1.component == component))
        |> Enum.map_join("\n", &row/1)

      """
      ## #{component}

      | what | kind | why |
      | --- | --- | --- |
      #{rows}
      """
    end)
  end

  defp row(%{kind: :configured} = entry),
    do: "| `#{entry.setting}` | named by a setting | #{entry.why} |"

  defp row(%{kind: :browser} = entry),
    do: "| `#{entry.host}` | the reader's browser | #{entry.why} |"

  defp row(entry), do: "| `#{entry.host}` | in the source | #{entry.why} |"
end
